services:
  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./devops/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  elasticsearch:
    image:  elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cat/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  etl_service:
    build:
      context: .
      dockerfile: devops/Dockerfile.etl
    container_name: etl_service
    env_file:
      - ./.env
    volumes:
      - etl_state:/app/state 
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5      

  fastapi:
    container_name: cinema_api
    build:
      context: .
      dockerfile: devops/Dockerfile.fa
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  etl_state: