FROM python:3.13
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

WORKDIR /app/tests
ENV PYTHONPATH=/app/tests

COPY tests/ /app/tests/

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked


CMD uv run pytest
