services:
  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5      

  auth:
    container_name: auth
    build:
      dockerfile: devops/Dockerfile.auth
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./devops/configs:/etc/nginx/conf.d:ro
    depends_on:
      - auth
    ports:
    - "8000:80"  
