[project]
name = "auth-service"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.1",
    "async-fastapi-jwt-auth>=0.6.6",
    "asyncpg>=0.31.0",
    "fastapi>=0.128.0",
    "gunicorn>=25.0.1",
    "opentelemetry-api>=1.39.1",
    "opentelemetry-exporter-jaeger>=1.21.0",
    "opentelemetry-instrumentation-fastapi>=0.60b1",
    "opentelemetry-sdk>=1.39.1",
    "orjson>=3.11.7",
    "passlib>=1.7.4",
    "pydantic-settings>=2.12.0",
    "redis>=7.1.0",
    "sqlalchemy[asyncio]>=2.0.45",
    "typer>=0.21.1",
    "uvicorn>=0.40.0",
    "werkzeug>=3.1.4",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
testpaths = ["tests"]
